name: stencil-golang
arguments:
  ciOptions:
    skipDocker: true
    skipE2e: true
  confluenceSpaceKey: DT
  description: Stencil Module for Golang Applications
  lifecycle: public_ga
  lintroller: platinum
  notifications:
    slackChannel: "#dt-notifications"
  plugin: true
  releaseOptions:
    allowMajorVersions: true
    autoPrereleases: true
    enablePrereleases: true
    force: true
    prereleasesBranch: main
  reportingTeam: fnd-dt
  tier: 2
modules:
  - name: github.com/getoutreach/stencil-template-base
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/stencil-base
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
replacements:
  github.com/getoutreach/stencil-golang: ./
