name: stencil-golang
modules:
  - name: github.com/getoutreach/stencil-template-base
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-base
arguments:
  reportingTeam: fnd-dt
  description: Stencil Module for Golang Applications
  releaseOptions:
    enablePrereleases: true
    allowMajorVersions: true
    prereleasesBranch: rc
