name: stencil-golang
arguments:
  ciOptions:
    skipDocker: true
    skipE2e: true
  reportingTeam: fnd-dt
  description: Stencil Module for Golang Applications
  plugin: true
  releaseOptions:
    force: true
    enablePrereleases: true
    prereleasesBranch: rc
  opslevel:
    confluenceSpaceKey: DT
    tier: 2
    lifecycle: public_ga
  lintroller: platinum
  notifications:
    slackChannel: "#dt-notifications"
modules:
  - name: github.com/getoutreach/stencil-template-base
    channel: rc
  - name: github.com/getoutreach/stencil-outreach # Required for opslevel.yml
    channel: rc
  - name: github.com/getoutreach/stencil-circleci
    channel: rc
  - name: github.com/getoutreach/stencil-base
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
