name: stencil-golang
arguments:
  ciOptions:
    skipDocker: true
    skipE2e: true
  reportingTeam: fnd-dt
  description: Stencil Module for Golang Applications
  plugin: true
  releaseOptions:
    force: true
    enablePrereleases: true
    prereleasesBranch: rc
  opslevel:
    confluenceSpaceKey: DT
    tier: 2
    lifecycle: public_ga
  lintroller: platinum
  notifications:
    slackChannel: "#dt-notifications"
replacements:
  github.com/getoutreach/stencil-golang: ./
modules:
  - name: github.com/getoutreach/stencil-template-base
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/devbase
    channel: main
  - name: github.com/getoutreach/stencil-golang
