// Code generated by {{ .tool }}. DO NOT EDIT.

// Package api is a helper package which defines the ping API
//
// This package is not meant to be used directly.  Clients should use
//
// github.com/getoutreach/{{ .repo }}/api/{{ .appName }}
// which implements a cleaner interface.
package api

// The following line(s) generate code using protobuf (e.g. {{ .appName }}.pb.go)
//
//go:generate ../scripts/shell-wrapper.sh protoc.sh

// The code that used to live in this file has been moved to a shared package,
// `github.com/getoutreach/services/pkg/grpcx`.
